version: '3.9'

#networks:
#  app-cluster:
#    name: app-cluster
#    driver: bridge

services:
  discovery-app:
    container_name: discovery-app
    image: discovery-service:1.0.0
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
#    networks:
#      - app-cluster
  gateway-app:
    container_name: gateway-app
    image: gateway-service:1.0.0
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
#    networks:
#      - app-cluster
#  order-app:
#    container_name: order-app
#    image: order-service:1.0.0
#    build:
#      context: ./order
#      dockerfile: Dockerfile
#    ports:
#      - "8090:8090"
#    networks:
#      - app-cluster